############################### 基本信息 ###############################
info:
  name: Material X
  docs: https://xaoxuu.com/wiki/material-x/
  cdn: # 把对应的那一行注释掉就使用本地的文件
    css:
      style: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-material-x@19.9.9/css/style.css
    js:
      app: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-material-x@19.9/js/app.js
      search: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-material-x@19.9/js/search.js
      volantis: https://cdn.jsdelivr.net/gh/xaoxuu/volantis@1.0.5/js/volantis.min.js

############################### 主题风格 ###############################
# style: material    # material: 导航栏和标题栏背景是主题色
style: pure # pure: 导航栏和标题栏背景是白色
word_count: true # 开启字数统计

############################### 服务开关 ###############################
scrollreveal: true
nodewaves: true
busuanzi: false
# fastclick: true

############################### 默认值 ###############################
# 音乐控件的默认配置，如果sidebar或者page里没有提供，就取这里的参数
music:
  enable: true # 是否启用
  color: "#1BCDFC" # 主题色
  mode: circulation # random （随机） single （单曲） circulation （列表循环） order （列表）
  server: netease # netease（网易云音乐）tencent（QQ音乐） xiami（虾米） kugou（酷狗）
  type: playlist # song （单曲） album （专辑） playlist （歌单） search （搜索）
  id: 2615636388 # 歌曲/专辑/歌单 ID
  volume: 0.7 # 音量, 0~1
  autoplay: false # 自动播放

# 友链页头像占位图
avatar_placeholder: https://tva1.sinaimg.cn/large/006tNbRwly1ga7tcgy34zj30eq0eqq32.jpg

# 日期格式 http://momentjs.com/docs/
date_format: "YYYY-MM-DD" # 文章发布日期的格式
updated_date_format: "ll" # 文章更新日期的格式

# 幻灯片
backstretch:
  position: cover # cover: 封面背景   full: 整个网页背景
  duration: 6000 # 持续时间（毫秒）
  fade: 2500 # 渐变（毫秒）
  images:
    - https://img.vim-cn.com/29/91197b04c13f512f734a76d4ac422d89dbe229.jpg

############################### 自定义 ###############################
# page的封面
cover:
  scheme: search # 后期将会提供多种封面方案
  height: half # full（默认值）: 首页封面占据整个第一屏幕，其他页面占半个屏幕高度， half: 所有页面都封面都只占半个屏幕高度
  title: lucifer
  # logo: assets/logo.png    # logo和title只显示一个，若同时设置，则只显示logo
  # search_placeholder: '搜索'
  # 主页封面菜单
  features:
    - name: 主页
      icon: fas fa-home
      url: /
    - name: 官网
      icon: fas fa-laptop-code
      url: http://leetcode-solution.cn/
    - name: 友链
      icon: fas fa-link
      url: friends/
    - name: 联系我
      icon: fas fa-id-card-alt
      url: about/

# 桌面端导航栏菜单
menu_desktop:
  - name: 回到主页
    icon: fas fa-grin
    url: /
  - name: 分类
    icon: fas fa-folder-open
    url: categories/
  - name: 标签
    icon: fas fa-hashtag
    url: tags/
  - name: 归档
    icon: fas fa-archive
    url: archives/

# 手机端导航菜单（从右上角的按钮点击展开）
menu_mobile:
  - name: 近期文章
    icon: fas fa-clock
    url: /
  - name: 文章归档
    icon: fas fa-archive
    url: archives/
  - name: 关于小站
    icon: fas fa-info-circle
    url: about/

layout:
  # 文章列表（主页、自定义的列表）布局
  posts:
    # 列表中每一篇文章的meta信息
    meta: [title, author, date, categories, top, word]
    # 列表类页面的侧边栏
    sidebar: [author, list, grid, category, tagcloud]
  # 文章页面布局
  article:
    # 文章页面主体元素，你也可以在页面的Front-matter中设置
    body: [article, comments]
    # 默认的meta信息，文章中没有配置则按照这里的配置来显示，设置为false则不显示
    # 其中，title只在header中有效，music和thumbnail无需在这里设置，文章中有则显示
    # 如果tags放置在meta.header中，那么在post列表中不显示（因为卡片下方已经有了）
    header: [title, author, date, categories, counter, top, word]
    footer: [updated, tags, share]
    # 文章页面的侧边栏
    sidebar: [author, toc, grid, category, tagcloud, list, related_posts]
  # 其他的页面布局暂时等于文章列表

# 侧边栏小部件配置
sidebar:
  - widget: author
    avartar: https://avatars0.githubusercontent.com/u/12479470?s=400&u=442571e44cbd0b67e3503e9551d4445c78f593f8&v=4
    social: true
  - widget: toc
  - widget: grid
    icon: fas fa-map-signs
    title: 我的开源项目
    rows:
      - name: LeetCode
        icon: fab fa-github
        url: https://github.com/azl397985856/leetcode
      - name: 大前端
        icon: fab fa-github
        url: https://github.com/azl397985856/fe-interview
      - name: 每日一荐
        icon: fab fa-github
        url: https://github.com/azl397985856/daily-featured
  - widget: category
    more:
      icon: fas fa-expand-arrows-alt
      url: categories/
  - widget: tagcloud
    icon: fas fa-tags
    more:
      icon: fas fa-expand-arrows-alt
      url: tags/
  # - widget: related_posts # 需要安装插件  npm i -S hexo-related-popular-posts
  - widget: music
    icon: fas fa-compact-disc
    title: "最近在听"
    more:
      icon: far fa-heart
      url: https://music.163.com/playlist?id=2649561572&userid=632167080
      rel: external nofollow noopener noreferrer
      target: _blank
    server: netease # netease（网易云音乐）tencent（QQ音乐） xiami（虾米） kugou（酷狗）
    type: playlist # song （单曲） album （专辑） playlist （歌单） search （搜索）
    id: 2615636388 # 歌曲/专辑/歌单 ID
  - widget: list
    icon: fas fa-thumbs-up
    title: 强烈推荐
    rows:
      - name: Hexo脚本（Mac）
        url: https://xaoxuu.com/wiki/hexo.sh/
      - name: 图床脚本（Mac）
        url: https://xaoxuu.com/wiki/vim-cn.sh/
      - name: 图片在线压缩
        url: https://yasuotu.com
      - name: 生成Favicon
        url: https://realfavicongenerator.net
      - name: 简历主题
        url: https://mxclub.github.io/resume/

# 社交信息
social:
  - icon: fas fa-rss
    url: atom.xml
  - icon: fab fa-zhihu
    url: https://www.zhihu.com/people/lu-xiao-13-70/activities
  - icon: fas fa-envelope
    url: mailto:azl397985856@gmail.com
  - icon: fab fa-github
    url: https://github.com/azl397985856
  - icon: fas fa-headphones-alt
    url: https://music.163.com/playlist?id=978545815&userid=632167080

# 分享按钮
# 当id为qrcode时需要安装插件  npm i -S hexo-helper-qrcode
share:
  - id: qrcode
    name: QRcode
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qrcode.png
  - id: qq
    name: QQ好友
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qq.png
  - id: qzone
    name: QQ空间
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qzone.png
  # - id: qrcode
  #   name: 微信
  #   img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/wechat.png
  - id: weibo
    name: 微博
    img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/weibo.png
  # - id: qrcode
  #   name: QRcode
  #   img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qrcode.png

# footer: '页脚文字，支持[markdown](/)'

############################### 评论系统 ###############################
# disqus_shortname: 要使用哪个请复制到根目录配置文件！
# livere_uid: 要使用哪个请复制到根目录配置文件！
# gitalk: 要使用哪个请复制到根目录配置文件！
#   clientID: 你的clientID
#   clientSecret: 你的clientSecret
#   repo: 你的repo名
#   owner: 你的GitHub名
#   admin: [] 至少填写你的GitHub名
# leancloud: 要使用哪个请复制到根目录配置文件！
#   app_id: 你的appId
#   app_key: 你的appKey

############################### 杂项，请勿删除 ###############################
#valine配置
valine:
  enable: true # 如果你想用Valine评论系统，请设置enable为true
  volantis: true # 是否启用volantis版本（禁止匿名，增加若干贴吧、QQ表情）
  # 还需要在根目录配置文件中添加下面这三行内容
  # leancloud:
  #   app_id: 你的appId
  #   app_key: 你的appKey
  guest_info: nick,mail,link #valine comment header info
  placeholder: 快来评论吧~ # valine comment input placeholder(like: Please leave your footprints )
  avatar: mp # gravatar style https://valine.js.org/avatar
  pageSize: 10 # comment list page size
  verify: true # valine verify code (true/false)
  notify: true # valine mail notify (true/false)
  lang: zh-cn
  highlight: true

# 搜索配置
search:
  enable: true
  service: hexo
  # google
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# Less渲染
less:
  compress: true
